- name: app setup
  include_role: 
    name: common
    tasks_from: appsetup.yaml

- name: nodejs setup
  include_role: 
    name: common
    tasks_from: nodejs.yaml



- name: copying mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present    

  # community.mongodb.mongodb_shell:
  #   file: /app/db/master-data.js
  #   idempotent: yes
  #   login_host: mongodb.raheemweb.fun

- name: check products loaded or not
  ansible.builtin.command:  mongosh --host mongodb.daws84s.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output


- name: printing the data
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: load products
  ansible.builtin.shell: mongosh --host mongodb.daws84s.site < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: systemd setup
  include_role: 
    name: common
    tasks_from: systemd.yaml


