- name: copying systemctl service file
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: daemond reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: starting the service
  ansible.builtin.service:
    name: catalogue
    enabled: yes
    state: restarted # even app is not running we can restart